### PR TITLE
Skyblock factory

### PR DESCRIPTION
**Pull request by AffeAli**
An early game single-block factory especially made for Skyblock. I just wanted to ask you if you want this in the mod so **please don't merge yet**.

### CODE REVIEW

**Comment by Ipsis** [comment]
Apologies, got a bit distracted with other things.
In short - in the nicest way possible, not really something I'd be looking to add.
I just don't think it fits in with the rest of the mod. The whole multiblock idea is pretty core to the mod.

I can only apologise, as you have put effort into your modification.

**Comment by AffeAli** [comment]
Should I change it into a cheaper multiblock than the mob factory or close the pull request?

**Comment by Ipsis** [comment]
What if we take a different approach.
What do you need that the current mod doesn't provide?
Are the recipes too expensive, is the way the factory operates not fit in with your requirements?

I'm really just trying to understand your requirements and if there is something else we could do, or if you are just trying to do something completely different than what I have in mind for the mod.

**Comment by AffeAli** [comment]
The idea was to provide a cheaper factory to shorten the ex nihilo (omnia) grind. Since it would take a long time to get all materials for a normal factory.
I thought you could use it as an replacement for these simlpe fall mab traps.

**Comment by Ipsis** [comment]
Looking over your code, it is more an additional block rather than a modification of the factory.

To be honest, I would just create your own standalone mod that contained your block and release that. It is not going to take you that much extra code to go from your pull request to a full mod.

**Comment by AffeAli** [comment]
I was thinking about making it a standalone mod but one block was not a lot content. Maybe I'm finding some things to add.

**Pull request closed without merging**
